language: node_js

cache:
  directories:
    - "node_modules"

script:
  cd website && npm install && npm run-script build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: website/build/documentation
  on:
    branch: docusaurus
